import { Response } from 'express';
import { assert, Infer, object, string } from 'superstruct';

import admin from '../db';
import { CustomRequest } from '../types/request';
import { handleError } from '../utils/handleError';
import { tinyId } from '../utils/uid';

const User = object({
  email: string(),
  name: string(),
  password: string(),
});

type CreateUserBody = Infer<typeof User>;

export const createUser = async (
  req: CustomRequest<CreateUserBody>,
  res: Response
) => {
  try {
    assert(req.body, User);

    const { email, password, name } = req.body;

    const autoGeneratedUsername = `${name
      .toLowerCase()
      .trim()
      .split(' ')
      .join('-')}-${tinyId()}`;

    const user = await admin.auth().createUser({
      email,
      password,
      displayName: autoGeneratedUsername,
    });

    return res.send({
      username: autoGeneratedUsername,
      email: user.email,
      name,
    });
  } catch (err) {
    const { code, message } = handleError(err);

    return res.status(code).send(message);
  }
};
