import { Response } from 'express';

import { db } from '../db';
import { CustomRequest } from '../types/request';
import { nanoid, tinyid } from '../utils/uid';

export interface CreateEventBody {
  name: string;
  location: string;
  emails: string[];
}

export const createEvent = async (
  req: CustomRequest<CreateEventBody>,
  res: Response
) => {
  const { name, location, emails } = req.body;

  const attendees = emails.map((email) => ({
    attending: false,
    email,
    replied: false,
    token: nanoid(),
  }));

  const uid = (req as any).authId;

  const userRef = db.collection('users').doc(uid);

  try {
    const autoGeneratedId = `${name.toLowerCase()}-${tinyid()}`;
    const newEvent = await userRef
      .collection('events')
      .doc(autoGeneratedId)
      .set({
        name,
        location,
        id: autoGeneratedId,
      });

    const eventRef = userRef.collection('events').doc(autoGeneratedId);

    await db.runTransaction(async (t) => {
      attendees.forEach((person) => {
        const attendeesRef = eventRef.collection('attendees').doc(person.token);
        t.create(attendeesRef, person);
      });
    });

    res.status(201).send(newEvent);
  } catch (err) {
    console.log('Failed on creating a new event', err);
    res.status(500).send('Internal Server Error');
  }
};
