import { Response } from 'express';

import admin, { db } from '../db';
import { CustomRequest } from '../types/request';
import { tinyid } from '../utils/uid';

export interface CreateUserBody {
  email: string;
  password: string;
  username: string;
  name: string;
}

export const createUser = async (
  req: CustomRequest<CreateUserBody>,
  res: Response
) => {
  try {
    const { email, password, username, name } = req.body;

    if (!email || !password || !username || !name) {
      return res.status(401).send('Not all details have been provided');
    }

    const autoGeneratedUsername = `${username.toLowerCase()}-${tinyid()}`;

    const user = await admin.auth().createUser({
      email,
      password,
    });

    await db.collection('users').doc(user.uid).set({
      displayName: name,
      internalUsername: autoGeneratedUsername,
      uid: user.uid,
    });

    return res.send({
      username: autoGeneratedUsername,
      email: user.email,
      name,
    });
  } catch (err) {
    console.log('Failed on creating a user', err);
    return res.status(500).send('Internal Server Error');
  }
};
